# Schemas package - All Pydantic schemas

from app.schemas.common import (
    BaseSchema,
    MessageResponse,
    ErrorResponse,
    PaginatedResponse,
    PaginationParams,
    HealthResponse,
)
from app.schemas.donor import (
    PersonalDetailsCreate,
    PersonalDetailsResponse,
    AddressDetailsCreate,
    AddressDetailsResponse,
    DiseaseDetailsCreate,
    DiseaseDetailsResponse,
    DonorCreate,
    DonorUpdate,
    DonorResponse,
    DonorListResponse,
    DonorLoginRequest,
    DonorLoginResponse,
    PasswordResetRequest,
    PasswordResetConfirm,
)
from app.schemas.admin import (
    AdminCreate,
    AdminUpdate,
    AdminResponse,
    AdminLoginRequest,
    AdminLoginResponse,
    AdminStatsResponse,
)
from app.schemas.blood_request import (
    BloodRequestStatus,
    HospitalCreate,
    HospitalUpdate,
    HospitalResponse,
    HospitalAutofillResponse,
    BloodRequestCreate,
    BloodRequestApprove,
    BloodRequestDecline,
    BloodRequestClose,
    BloodRequestResponse,
    BloodRequestListResponse,
    ResponseDetailsCreate,
    ResponseDetailsResponse,
)

__all__ = [
    # Common
    "BaseSchema",
    "MessageResponse",
    "ErrorResponse",
    "PaginatedResponse",
    "PaginationParams",
    "HealthResponse",
    # Donor
    "PersonalDetailsCreate",
    "PersonalDetailsResponse",
    "AddressDetailsCreate",
    "AddressDetailsResponse",
    "DiseaseDetailsCreate",
    "DiseaseDetailsResponse",
    "DonorCreate",
    "DonorUpdate",
    "DonorResponse",
    "DonorListResponse",
    "DonorLoginRequest",
    "DonorLoginResponse",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    # Admin
    "AdminCreate",
    "AdminUpdate",
    "AdminResponse",
    "AdminLoginRequest",
    "AdminLoginResponse",
    "AdminStatsResponse",
    # Blood Request
    "BloodRequestStatus",
    "HospitalCreate",
    "HospitalUpdate",
    "HospitalResponse",
    "HospitalAutofillResponse",
    "BloodRequestCreate",
    "BloodRequestApprove",
    "BloodRequestDecline",
    "BloodRequestClose",
    "BloodRequestResponse",
    "BloodRequestListResponse",
    "ResponseDetailsCreate",
    "ResponseDetailsResponse",
]
